In [42]:
daily_sales = np.array([100, 105, 110, 120, 125, 130, 140, 145, 150, 160,
               165, 170, 180, 185, 190, 200, 205, 210, 220, 225])

In [43]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [44]:
x = daily_sales/1000.0
x

array([0.1  , 0.105, 0.11 , 0.12 , 0.125, 0.13 , 0.14 , 0.145, 0.15 ,
       0.16 , 0.165, 0.17 , 0.18 , 0.185, 0.19 , 0.2  , 0.205, 0.21 ,
       0.22 , 0.225])

In [45]:
X = []
y = []
window = 4

for i in range(len(daily_sales)-window):
    X.append(x[i:i+window])
    y.append(x[i+window])
X = np.array(X).reshape(-1,window,1)
y = np.array(y)


In [46]:
X

array([[[0.1  ],
        [0.105],
        [0.11 ],
        [0.12 ]],

       [[0.105],
        [0.11 ],
        [0.12 ],
        [0.125]],

       [[0.11 ],
        [0.12 ],
        [0.125],
        [0.13 ]],

       [[0.12 ],
        [0.125],
        [0.13 ],
        [0.14 ]],

       [[0.125],
        [0.13 ],
        [0.14 ],
        [0.145]],

       [[0.13 ],
        [0.14 ],
        [0.145],
        [0.15 ]],

       [[0.14 ],
        [0.145],
        [0.15 ],
        [0.16 ]],

       [[0.145],
        [0.15 ],
        [0.16 ],
        [0.165]],

       [[0.15 ],
        [0.16 ],
        [0.165],
        [0.17 ]],

       [[0.16 ],
        [0.165],
        [0.17 ],
        [0.18 ]],

       [[0.165],
        [0.17 ],
        [0.18 ],
        [0.185]],

       [[0.17 ],
        [0.18 ],
        [0.185],
        [0.19 ]],

       [[0.18 ],
        [0.185],
        [0.19 ],
        [0.2  ]],

       [[0.185],
        [0.19 ],
        [0.2  ],
        [0.205]],

       [[0.19 ],
   

In [47]:
y

array([0.125, 0.13 , 0.14 , 0.145, 0.15 , 0.16 , 0.165, 0.17 , 0.18 ,
       0.185, 0.19 , 0.2  , 0.205, 0.21 , 0.22 , 0.225])

In [48]:
from tensorflow.keras.layers import LSTM,Dense,SimpleRNN
from tensorflow.keras.models import Sequential

model = Sequential([
    LSTM(32,activation='tanh',input_shape=(window,1)),
    Dense(1)
])

c:\Users\MINA\miniconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [49]:
model.compile(optimizer='adam',loss='mse')

In [50]:
model.fit(X,y,epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 0.0328
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 0.0297
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0269
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0242
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.0216
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0192
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0170
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0149
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.0130
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0112
