In [1]:
import numpy as np

In [2]:
X = [1, 2, 3]

In [3]:
U = np.random.randn(1)
W = np.random.randn(1)
V = np.random.randn(1)

In [4]:
h = 0

In [5]:
for x in X:
    h = np.tanh(U * x + W * h)
    y = V * h

print("Input :", x)
print("Hidden:", h)
print("Output:", y)
print("----------------")

Input : 3
Hidden: [0.9993969]
Output: [-0.54318765]
----------------


# Project 2

In [6]:
import numpy as np 
np.random.seed(42)

In [7]:
X = [1,2,3]


In [ ]:
input_size = 1
hidden_size = 2
output_size = 1 

In [ ]:
# input to hidden
U = np.random.randn(hidden_size, input_size)
print(U) 

[[ 0.49671415]
 [-0.1382643 ]]


In [10]:
# hidden to hidden
W = np.random.randn(hidden_size,hidden_size)
print(W)

[[ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]]


In [11]:
#Hidden to Output
V = np.random.randn(output_size,hidden_size)
print(V)

[[1.57921282 0.76743473]]


In [12]:
h = np.zeros((hidden_size,1))
print(h)

[[0.]
 [0.]]


In [13]:
x = np.array([[X[0]]])
print(x)

[[1]]


In [14]:
h = np.tanh(U@x+W@h)
print(h)

[[ 0.45952909]
 [-0.13738992]]


In [15]:
h = np.zeros((hidden_size,1))

for value in X:
    x = np.array([[value]])

    #hidden state
    h = np.tanh(U@x + W@h)

    #output 
    y=V@h 

    print("----------------")
    print("Input")
    print(x)

    print("\nHidden State")
    print(h)

    print("\nOutput")
    print(y)

----------------
Input
[[1]]

Hidden State
[[ 0.45952909]
 [-0.13738992]]

Output
[[0.62025643]]
----------------
Input
[[2]]

Hidden State
[[ 0.79386975]
 [-0.33811336]]

Output
[[0.99420934]]
----------------
Input
[[3]]

Hidden State
[[ 0.90320803]
 [-0.47886872]]

Output
[[1.05885721]]
