In [1]:
text = """
i love mechine learning
mechine learning is a branch if Artificial intelligence
mechine learning is fantastic
deep learning is a type of mechine learning
"""

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

## 1. Tokenization

In [3]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1

print('Total words:',total_words)
print(tokenizer.word_index)

Total words: 15
{'learning': 1, 'mechine': 2, 'is': 3, 'a': 4, 'i': 5, 'love': 6, 'branch': 7, 'if': 8, 'artificial': 9, 'intelligence': 10, 'fantastic': 11, 'deep': 12, 'type': 13, 'of': 14}


## 2. Create Input Sequence

In [ ]:
input_sequence = []
for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequence.append(sequence)
print(input_sequence)
    

NameError: name 'texts' is not defined

## 3. Pad Sequence

In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_sequence_len = max(len(seq) for seq in input_sequence)

input_sequence = pad_sequences(
    input_sequence,
    maxlen = max_sequence_len,
    padding = 'pre'
)
print(input_sequence)

[[ 0  0  0  0  0  0  5  6]
 [ 0  0  0  0  0  5  6  2]
 [ 0  0  0  0  5  6  2  1]
 [ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  3]
 [ 0  0  0  0  2  1  3  4]
 [ 0  0  0  2  1  3  4  7]
 [ 0  0  2  1  3  4  7  8]
 [ 0  2  1  3  4  7  8  9]
 [ 2  1  3  4  7  8  9 10]
 [ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  3]
 [ 0  0  0  0  2  1  3 11]
 [ 0  0  0  0  0  0 12  1]
 [ 0  0  0  0  0 12  1  3]
 [ 0  0  0  0 12  1  3  4]
 [ 0  0  0 12  1  3  4 13]
 [ 0  0 12  1  3  4 13 14]
 [ 0 12  1  3  4 13 14  2]
 [12  1  3  4 13 14  2  1]]


## 4. Saperate X & y

In [10]:
X = input_sequence[:,:-1]
y = input_sequence[:,-1]
print('X',X)
print('y',y)

X [[ 0  0  0  0  0  0  5]
 [ 0  0  0  0  0  5  6]
 [ 0  0  0  0  5  6  2]
 [ 0  0  0  0  0  0  2]
 [ 0  0  0  0  0  2  1]
 [ 0  0  0  0  2  1  3]
 [ 0  0  0  2  1  3  4]
 [ 0  0  2  1  3  4  7]
 [ 0  2  1  3  4  7  8]
 [ 2  1  3  4  7  8  9]
 [ 0  0  0  0  0  0  2]
 [ 0  0  0  0  0  2  1]
 [ 0  0  0  0  2  1  3]
 [ 0  0  0  0  0  0 12]
 [ 0  0  0  0  0 12  1]
 [ 0  0  0  0 12  1  3]
 [ 0  0  0 12  1  3  4]
 [ 0  0 12  1  3  4 13]
 [ 0 12  1  3  4 13 14]
 [12  1  3  4 13 14  2]]
y [ 6  2  1  1  3  4  7  8  9 10  1  3 11  1  3  4 13 14  2  1]


## 5. One-Hot Encoding

In [11]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes = total_words)
y

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.

## 6. Build RNN

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Embedding, Dense 

model = Sequential()

model.add(Embedding(total_words, 10, input_length=max_sequence_len-1))

model.add(SimpleRNN(100))

model.add(Dense(total_words, activation='softmax'))



c:\Users\MINA\miniconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

In [15]:
model.fit(X,y,epochs=200,verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 2.7072
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.2500 - loss: 2.6844
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3000 - loss: 2.6607
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.3000 - loss: 2.6351
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.3000 - loss: 2.6062
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3000 - loss: 2.5732
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.2500 - loss: 2.5348
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 2.4906
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.2500 - loss: 2.4411
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.2500 - loss: 2.3890
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.2500 - loss: 2.3404
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.2500 - 

In [17]:
import numpy as np
#Generate text
seed_text = 'mechine learning'
next_word = 6

for _ in range(next_word):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len-1,
        padding='pre'
    )
    predicted = np.argmax(
        model.predict(token_list,verbose=0),
        axis=-1
    )[0]

    output_word = ""
    
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word 
            break 
    seed_text += " " + output_word
print(seed_text)

mechine learning is a branch if artificial intelligence
