In [1]:
import tensorflow as tf 
from tensorflow  import keras 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [2]:
text = """
i love mechine learning
mechine learning is a branch of Artificial intelligence
mechine learning is fantastic
deep learning is a type of mechine learning
"""

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index)+1

print(total_words)
print(tokenizer.word_index)

14
{'learning': 1, 'mechine': 2, 'is': 3, 'a': 4, 'of': 5, 'i': 6, 'love': 7, 'branch': 8, 'artificial': 9, 'intelligence': 10, 'fantastic': 11, 'deep': 12, 'type': 13}


In [5]:
input_sequences = []
for line in text.split('\n'):
    text_seq = tokenizer.texts_to_sequences([line])[0]

    for i in range(1,len(text_seq)):
        sequence = text_seq[:i+1]
        input_sequences.append(sequence)
print(input_sequences)

[[6, 7], [6, 7, 2], [6, 7, 2, 1], [2, 1], [2, 1, 3], [2, 1, 3, 4], [2, 1, 3, 4, 8], [2, 1, 3, 4, 8, 5], [2, 1, 3, 4, 8, 5, 9], [2, 1, 3, 4, 8, 5, 9, 10], [2, 1], [2, 1, 3], [2, 1, 3, 11], [12, 1], [12, 1, 3], [12, 1, 3, 4], [12, 1, 3, 4, 13], [12, 1, 3, 4, 13, 5], [12, 1, 3, 4, 13, 5, 2], [12, 1, 3, 4, 13, 5, 2, 1]]


In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences 

max_seqence_len = max(len(seq) for seq in input_sequences)

input_sequences = pad_sequences(
    input_sequences,
    maxlen = max_seqence_len,
    padding = 'pre'
)
print(input_sequences)

[[ 0  0  0  0  0  0  6  7]
 [ 0  0  0  0  0  6  7  2]
 [ 0  0  0  0  6  7  2  1]
 [ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  3]
 [ 0  0  0  0  2  1  3  4]
 [ 0  0  0  2  1  3  4  8]
 [ 0  0  2  1  3  4  8  5]
 [ 0  2  1  3  4  8  5  9]
 [ 2  1  3  4  8  5  9 10]
 [ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  3]
 [ 0  0  0  0  2  1  3 11]
 [ 0  0  0  0  0  0 12  1]
 [ 0  0  0  0  0 12  1  3]
 [ 0  0  0  0 12  1  3  4]
 [ 0  0  0 12  1  3  4 13]
 [ 0  0 12  1  3  4 13  5]
 [ 0 12  1  3  4 13  5  2]
 [12  1  3  4 13  5  2  1]]


In [7]:
X = input_sequences[:,:-1]
y = input_sequences[:,-1]

In [8]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes=total_words)

In [9]:
y

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1

In [10]:
model = Sequential()
model.add(Embedding(total_words,10,input_length=max_seqence_len-1))
model.add(SimpleRNN(100))
model.add(Dense(total_words,activation='sigmoid'))


In [11]:
model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

In [12]:
model.fit(X,y,epochs=200,verbose=1)

Epoch 1/200
1/1 [==============================] - 3s 3s/step - loss: 2.6466 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 8ms/step - loss: 2.6194 - accuracy: 0.2000
Epoch 3/200
1/1 [==============================] - 0s 12ms/step - loss: 2.5915 - accuracy: 0.2000
Epoch 4/200
1/1 [==============================] - 0s 8ms/step - loss: 2.5616 - accuracy: 0.2500
Epoch 5/200
1/1 [==============================] - 0s 11ms/step - loss: 2.5283 - accuracy: 0.2500
Epoch 6/200
1/1 [==============================] - 0s 11ms/step - loss: 2.4907 - accuracy: 0.2500
Epoch 7/200
1/1 [==============================] - 0s 10ms/step - loss: 2.4482 - accuracy: 0.2500
Epoch 8/200
1/1 [==============================] - 0s 13ms/step - loss: 2.4012 - accuracy: 0.2500
Epoch 9/200
1/1 [==============================] - 0s 23ms/step - loss: 2.3524 - accuracy: 0.2500
Epoch 10/200
1/1 [==============================] - 0s 10ms/step - loss: 2.3074 - accuracy: 0.2500
Epoch 11/200
1/1 [=

In [14]:
import numpy as np

seed_text = 'mechine learning'
next_word = 6

for _ in range(next_word):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list],maxlen=max_seqence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list,verbose=0), axis=-1)[0]

    output_word = ""
    for word,index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    seed_text += " "+output_word
print(seed_text)

mechine learning is a branch of artificial intelligence


In [ ]:
import numpy as np
#Generate text
seed_text = 'mechine learning'
next_word = 6

for _ in range(next_word):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len-1,
        padding='pre'
    )
    predicted = np.argmax(
        model.predict(token_list,verbose=0),
        axis=-1
    )[0]

    output_word = ""
    
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word 
            break 
    seed_text += " " + output_word
print(seed_text)