In [17]:
import numpy as np
import tensorflow as tf 
from tensorflow import keras

from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense 
from tensorflow.keras.preprocessing.text import Tokenizer 
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [18]:
text = """
machine learning is a fascinating field
machine learning helps computers learn from data
deep learning is a part of machine learning
artificial intelligence is changing the world
"""

print(text)


machine learning is a fascinating field
machine learning helps computers learn from data
deep learning is a part of machine learning
artificial intelligence is changing the world



### Tokenize the Text

In [19]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1

print('Total words:',total_words)
print(tokenizer.word_index)

Total words: 20
{'learning': 1, 'machine': 2, 'is': 3, 'a': 4, 'fascinating': 5, 'field': 6, 'helps': 7, 'computers': 8, 'learn': 9, 'from': 10, 'data': 11, 'deep': 12, 'part': 13, 'of': 14, 'artificial': 15, 'intelligence': 16, 'changing': 17, 'the': 18, 'world': 19}


### Create Input Sequences

In [20]:
input_sequences = []
for line in text.split("\n"):
    token_list = tokenizer.texts_to_sequences([line])[0] 

    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequences.append(sequence)
print(input_sequences)


[[2, 1], [2, 1, 3], [2, 1, 3, 4], [2, 1, 3, 4, 5], [2, 1, 3, 4, 5, 6], [2, 1], [2, 1, 7], [2, 1, 7, 8], [2, 1, 7, 8, 9], [2, 1, 7, 8, 9, 10], [2, 1, 7, 8, 9, 10, 11], [12, 1], [12, 1, 3], [12, 1, 3, 4], [12, 1, 3, 4, 13], [12, 1, 3, 4, 13, 14], [12, 1, 3, 4, 13, 14, 2], [12, 1, 3, 4, 13, 14, 2, 1], [15, 16], [15, 16, 3], [15, 16, 3, 17], [15, 16, 3, 17, 18], [15, 16, 3, 17, 18, 19]]


### Pad the Sequences

In [ ]:
max_sequence_len = max(len(seq) for seq in input_sequences)

input_sequences = pad_sequences(  #add extra values(0) to make every seq the same leng
    input_sequences,
    maxlen=max_sequence_len,
    padding='pre' #add values before 0
)
print(input_sequences)

[[ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  3]
 [ 0  0  0  0  2  1  3  4]
 [ 0  0  0  2  1  3  4  5]
 [ 0  0  2  1  3  4  5  6]
 [ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  7]
 [ 0  0  0  0  2  1  7  8]
 [ 0  0  0  2  1  7  8  9]
 [ 0  0  2  1  7  8  9 10]
 [ 0  2  1  7  8  9 10 11]
 [ 0  0  0  0  0  0 12  1]
 [ 0  0  0  0  0 12  1  3]
 [ 0  0  0  0 12  1  3  4]
 [ 0  0  0 12  1  3  4 13]
 [ 0  0 12  1  3  4 13 14]
 [ 0 12  1  3  4 13 14  2]
 [12  1  3  4 13 14  2  1]
 [ 0  0  0  0  0  0 15 16]
 [ 0  0  0  0  0 15 16  3]
 [ 0  0  0  0 15 16  3 17]
 [ 0  0  0 15 16  3 17 18]
 [ 0  0 15 16  3 17 18 19]]


### Separate Input ans Output

In [26]:
X = input_sequences[: , :-1]
y = input_sequences[: , -1]

print('X:')
print(X)

print('\ny:')
print(y)

X:
[[ 0  0  0  0  0  0  2]
 [ 0  0  0  0  0  2  1]
 [ 0  0  0  0  2  1  3]
 [ 0  0  0  2  1  3  4]
 [ 0  0  2  1  3  4  5]
 [ 0  0  0  0  0  0  2]
 [ 0  0  0  0  0  2  1]
 [ 0  0  0  0  2  1  7]
 [ 0  0  0  2  1  7  8]
 [ 0  0  2  1  7  8  9]
 [ 0  2  1  7  8  9 10]
 [ 0  0  0  0  0  0 12]
 [ 0  0  0  0  0 12  1]
 [ 0  0  0  0 12  1  3]
 [ 0  0  0 12  1  3  4]
 [ 0  0 12  1  3  4 13]
 [ 0 12  1  3  4 13 14]
 [12  1  3  4 13 14  2]
 [ 0  0  0  0  0  0 15]
 [ 0  0  0  0  0 15 16]
 [ 0  0  0  0 15 16  3]
 [ 0  0  0 15 16  3 17]
 [ 0  0 15 16  3 17 18]]

y:
[ 1  3  4  5  6  1  7  8  9 10 11  1  3  4 13 14  2  1 16  3 17 18 19]


### Convert Output to One-Hot Encoding

In [27]:
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

print(y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.

### Build the RNN Model

In [28]:
model = Sequential([
    Embedding(
        input_dim=total_words,
        output_dim=10,
        input_length=max_sequence_len - 1
    ),
    SimpleRNN(50),
    Dense(total_words, activation='softmax')
])

c:\Users\MINA\miniconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [29]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [30]:
history = model.fit(
    X,y,epochs=200,verbose=1
)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0435 - loss: 2.9889
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.2174 - loss: 2.9734
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.2174 - loss: 2.9572
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.2174 - loss: 2.9400
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.1304 - loss: 2.9216
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.1739 - loss: 2.9015
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1739 - loss: 2.8798
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.1739 - loss: 2.8562
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.1739 - loss: 2.8309
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.1739 - loss: 2.8041
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.1739 - loss: 2.7766
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.1739 - loss

### Generate Text

In [ ]:
seed_text = 'mechine'

next_words = 5

for _ in range(next_words):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]

    token_list = pad_sequences(
        [token_list],
        maxlen = max_sequence_len - 1,
        padding='pre'
    )

    predicted = np.argmax(
        model.predict(token_list, verbose=0),
        axis=-1
    )[0]

    output_word = ""

    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word 
            break 
    seed_text += " " + output_word
print(seed_text)

mechine learning learning is a part


# Project 2

In [50]:
text = """
machine learning is a fascinating field
machine learning helps computers learn from data
deep learning is a part of machine learning
artificial intelligence is changing the world
"""

In [51]:
from tensorflow.keras.preprocessing.text import Tokenizer 

tokenizer.fit_on_texts([text])

print(tokenizer.word_index)

{'learning': 1, 'machine': 2, 'is': 3, 'a': 4, 'fascinating': 5, 'field': 6, 'helps': 7, 'computers': 8, 'learn': 9, 'from': 10, 'data': 11, 'deep': 12, 'part': 13, 'of': 14, 'artificial': 15, 'intelligence': 16, 'changing': 17, 'the': 18, 'world': 19}


In [52]:
#Create sequences
input_seq = []

for line in text.split('\n'):

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_seq.append(sequence)
print(input_seq)


[[2, 1], [2, 1, 3], [2, 1, 3, 4], [2, 1, 3, 4, 5], [2, 1, 3, 4, 5, 6], [2, 1], [2, 1, 7], [2, 1, 7, 8], [2, 1, 7, 8, 9], [2, 1, 7, 8, 9, 10], [2, 1, 7, 8, 9, 10, 11], [12, 1], [12, 1, 3], [12, 1, 3, 4], [12, 1, 3, 4, 13], [12, 1, 3, 4, 13, 14], [12, 1, 3, 4, 13, 14, 2], [12, 1, 3, 4, 13, 14, 2, 1], [15, 16], [15, 16, 3], [15, 16, 3, 17], [15, 16, 3, 17, 18], [15, 16, 3, 17, 18, 19]]


In [53]:
#Find the longest sequence
max_sequence_len = max(len(sequence) for seq in input_sequences)
print(max_sequence_len)

6


In [56]:
#Padding 
from tensorflow.keras.preprocessing.sequence import pad_sequences

input_sequences = pad_sequences(
    input_sequences,
    maxlen = max_sequence_len,
    padding='pre'
)

print(input_sequences)

[[ 0  0  0  0  2  1]
 [ 0  0  0  2  1  3]
 [ 0  0  2  1  3  4]
 [ 0  2  1  3  4  5]
 [ 2  1  3  4  5  6]
 [ 0  0  0  0  2  1]
 [ 0  0  0  2  1  7]
 [ 0  0  2  1  7  8]
 [ 0  2  1  7  8  9]
 [ 2  1  7  8  9 10]
 [ 1  7  8  9 10 11]
 [ 0  0  0  0 12  1]
 [ 0  0  0 12  1  3]
 [ 0  0 12  1  3  4]
 [ 0 12  1  3  4 13]
 [12  1  3  4 13 14]
 [ 1  3  4 13 14  2]
 [ 3  4 13 14  2  1]
 [ 0  0  0  0 15 16]
 [ 0  0  0 15 16  3]
 [ 0  0 15 16  3 17]
 [ 0 15 16  3 17 18]
 [15 16  3 17 18 19]]


In [55]:
#Separate X and y 
X = input_sequences[:,:-1]
y = input_sequences[:,-1]

In [57]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes = total_words)

In [58]:
#Build RNN
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

model = Sequential()

model.add(Embedding(total_words, 10, input_length=max_sequence_len-1))

model.add(SimpleRNN(100))

model.add(Dense(total_words, activation='softmax'))


c:\Users\MINA\miniconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [59]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
    )

In [60]:
model.fit(X,y,epochs=200,verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 3.0053
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.0870 - loss: 2.9863
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.0870 - loss: 2.9675
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.1739 - loss: 2.9482
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.2174 - loss: 2.9279
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.1739 - loss: 2.9060
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.1739 - loss: 2.8819
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.1739 - loss: 2.8551
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.1739 - loss: 2.8250
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.1739 - loss: 2.7913
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.1739 - loss: 2.7538
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.1739 -

In [61]:
#Generate text
seed_text = 'mechine learning'
next_word = 5

for _ in range(next_words):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len-1,
        padding='pre'
    )
    predicted = np.argmax(
        model.predict(token_list,verbose=0),
        axis=-1
    )[0]

    output_word = ""
    
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word 
            break 
    seed_text += " " + output_word
print(seed_text)

mechine learning intelligence is changing the world


i love cats,
i have food 
