In [6]:
import numpy as np
import pandas as pd 
import tensorflow as tf 
from tensorflow import keras
from tensorflow.keras import layers 

translation

In [7]:
#Create token IDs
I=1
love=2
cats=3
animals=4

X = np.array([[I,love,cats]])
y = np.array([[I,love,animals]])

In [8]:
############################Build Transformer###################################
vocab_size = 5
embed_dim = 8 

inputs = keras.Input(shape=(3,))

#Embedding 
x = layers.Embedding(vocab_size, embed_dim)(inputs)

#self-attention 
attention = layers.MultiHeadAttention(
    num_heads=2,
    key_dim=8
)(x,x) 

#Add & Norm 
x = layers.LayerNormalization()(x + attention) 

#Feed Forward 
ffn = layers.Dense(16, activation='relu')(x)
ffn = layers.Dense(8)(ffn)

#Add & Norm
x = layers.LayerNormalization()(x + ffn) 

#outputs
outputs = layers.Dense(vocab_size, activation='softmax')(x)

model = keras.Model(inputs,outputs)

In [9]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [10]:
model.fit(X,y,epochs=100,verbose=0)

In [11]:
preidction = model.predict(X)
print(preidction.shape)

1/1 [==============================] - 0s 211ms/step
(1, 3, 5)


In [14]:
preidcted_ids = np.argmax(preidction, axis=-1)
print(preidcted_ids)

[[1 2 4]]


In [15]:
id_to_word = {
    1: "I",
    2: "love",
    3: "cats",
    4: "animals"
}

In [16]:
predicted_sentence = " ".join(id_to_word[i] for i in preidcted_ids[0])

print(predicted_sentence)

I love animals


______________________________________________________________________________________________________________________________________________________

# Practical 2

In [17]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [18]:
english = [
    "I love cats",
    "I love dogs",
    "I like cats",
    "I like dogs"
]

french = [
    "J'aime les chats",
    "J'aime les chiens",
    "J'aime les chats",
    "J'aime les chiens"
]

In [19]:
# English token IDs
I = 1
love = 2
cats = 3

# French token IDs
jaime = 1
les = 2
chats = 3

In [20]:
X = np.array([[1,2,3]])
y = np.array([[1,2,3]])

In [23]:
vocab_size = 4
embed_dim = 8 

inputs = keras.Input(shape=(3,))

#Embedding 
x = layers.Embedding(vocab_size,embed_dim)(inputs)

#Self Attention
attention = layers.MultiHeadAttention(
    num_heads=2,
    key_dim=8
)(x,x)

#Add & Norm 
x = layers.LayerNormalization()(x + attention)

#Feed Forward 
ffn = layers.Dense(16, activation='relu')(x)
ffn = layers.Dense(embed_dim)(ffn) 

#Add & Norms 
x = layers.LayerNormalization()(x+ffn) 

#Output Layer 
outputs = layers.Dense(vocab_size, activation='softmax')(x)
model = keras.Model(inputs,outputs)

# Practical 3

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [16]:
I = 0
love = 1
cats = 2
animals = 3

X = np.array([[I,love,cats]])

y = np.array([[I,love,animals]])

In [22]:
#Build Transformer
vocab_size = 4
embed_dim = 8 

inputs = keras.Input(shape=(3,))

#Embedding
x = layers.Embedding(vocab_size,embed_dim)(inputs)
#self attention
attention = layers.MultiHeadAttention(num_heads=2,key_dim=8)(x,x)
#Add&Norm
x = layers.LayerNormalization()(x+attention)
#FeedForward
ffn = layers.Dense(16, activation='relu')(x)
ffn = layers.Dense(8)(ffn)
#Add & Norm
x = layers.LayerNormalization()(x+ffn)
#output
# outputs = layers.Dense(5,activation='sigmoid')(x)
outputs = layers.Dense(vocab_size,activation='softmax')(x)

model = keras.Model(inputs,outputs)

In [23]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [24]:
model.fit(X,y,epochs=100,verbose=0)

In [27]:
prediction = model.predict(X)
prediction

1/1 [==============================] - 0s 23ms/step


array([[[0.92559016, 0.00932056, 0.02590491, 0.03918431],
        [0.01189959, 0.9627524 , 0.01892472, 0.00642329],
        [0.02568385, 0.01728757, 0.02346917, 0.93355936]]], dtype=float32)

In [29]:
predicted_id = np.argmax(prediction,axis=-1)
print(predicted_id)

[[0 1 3]]
